import manifolds_metrics_especially_riemannian_theorem_canonical_lane_mathlib.GateLemmas
namespace HautevilleHouse
namespace manifolds_metrics_especially_riemannian_theorem_canonical_lane_mathlib
structure ConstrainedTheoremClosure where
  admissible :: intro :: constraint :: consequence :: proof ::
theorem canonical : ConstrainedTheoremClosure :=
  ConstrainedTheoremClosure.intro
end manifolds_metrics_especially_riemannian_theorem_canonical_lane_mathlib
end HautevilleHouse
